### EKF Sensor Fusion Configuration ###
# IMUとオドメトリを融合して、より安定した自己位置推定を実現
ekf_filter_node:
  ros__parameters:
    use_sim_time: true
    # フレーム設定
    map_frame: map
    odom_frame: sirius3/odom
    base_link_frame: sirius3/base_footprint
    world_frame: sirius3/odom
    # 更新周波数（シミュレータに合わせて低めに設定）
    frequency: 20.0
    # センサータイムアウト（余裕を持たせる）
    sensor_timeout: 0.2
    # 2D/3Dモード（安定性のため2Dモードに変更）
    two_d_mode: true
    
    # オドメトリ
    odom0: /odom
    odom0_config: [true, true, false, # x, y, z
                  false, false, false, # roll, pitch, yaw
                  true,  true,  false, # vx, vy, vz
                  false, false, true, # vroll, vpitch, vyaw
                  false, false, false] # ax, ay, az
    odom0_queue_size: 10
    odom0_differential: false # 位置は絶対値
    odom0_relative: false # 絶対値
    
    # IMU
    imu0: /imu
    imu0_config: [false, false, false,  # x, y, z
                  false, false, true,  # roll, pitch, yaw
                  false, false, false,  # vx, vy, vz
                  false, false, true,   # vroll, vpitch, vyaw
                  false, false, false]  # ax, ay, az
    imu0_queue_size: 10
    imu0_differential: true # 角度は差分
    imu0_relative: true   # 相対値
    imu0_remove_gravitational_acceleration: true # 重力加速度9.8m/s^2を除去

    # プロセスノイズ共分散行列（15x15の対角行列）
    # 各状態変数の不確実性を表現
    process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.06, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.025,0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.04, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.02, 0.0,  0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,
                                0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.015]
    
    # 診断とデバッグ用設定
    publish_tf: true             
    publish_acceleration: false   # 加速度情報は配信しない
    print_diagnostics: true       # 診断情報を出力
    
    # 高度な設定
    predict_to_current_time: true
    smooth_lagged_data: false

# ros2 run robot_localization ekf_node --ros-args --params-file ~/sirius_jazzy_ws/params/ekf_fusion.yaml --ros-args --log-level info

# ┌─────────────┬──────────────┬───────────────────┐
# │ 情報         │ センサー      │ 理由              │
# ├─────────────┼──────────────┼───────────────────┤
# │ 位置 (x,y)   │ オドメトリ     │ 車輪で正確に計測    │
# ├─────────────┼──────────────┼───────────────────┤
# │ 速度 (vx,vy) │ オドメトリ     │ 車輪の回転速度      │
# ├─────────────┼──────────────┼───────────────────┤
# │ 姿勢 (yaw)   │ IMU (差分)   │ 回転検出が得意       │
# ├─────────────┼──────────────┼───────────────────┤
# │ 角速度(vyaw) │ オドメ + IMU  │ 両方で補完          │
# └─────────────┴──────────────┴───────────────────┘