slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # プラグインパラメータ
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROSパラメータ
    odom_frame: sirius3/odom
    map_frame: map
    base_frame: sirius3/base_footprint
    scan_topic: /scan3
    use_map_saver: true
    mode: mapping

    debug_logging: true
    # Reduce input rate in sim to better match hardware test and lower processing
    throttle_scans: 0  # process 1 out of 5 scans
    transform_publish_period: 0.02
    map_update_interval: 3.0  # マップ更新を高速化(5.0秒→1.0秒)
    resolution: 0.05
    min_laser_range: 1.0
    max_laser_range: 30.0  # Unityでの不安定な遠方点を除外するため100mから短縮
    
    # TF関連 - より寛容な設定
    transform_timeout: 1.0  # より寛容に
    # Allow longer TF buffering to tolerate transform arrival jitter
    tf_buffer_duration: 60.0
    
    # メッセージ処理関連
    minimum_time_interval: 0.1      # 0.1秒ごとに必ず処理
    minimum_laser_range: 0.0
    
    stack_size_to_use: 100000000
    enable_interactive_mode: true
    
    # 一般的なパラメータ
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.2   # Unityでの連続性を高めるため0.3から短縮
    minimum_travel_heading: 0.2     # Unityでの連続性を高めるため0.3から短縮
    scan_buffer_size: 20  # 通信ジッタ対策のため10から増加
    scan_buffer_maximum_scan_distance: 20.0  # より厳格に
    link_match_minimum_response_fine: 0.1  # より厳格に(0.1→0.4)
    link_scan_maximum_distance: 1.5  # 探索範囲を広げる
    loop_search_maximum_distance: 5.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45 # 0.45 -> 0.55 より確信度が高い

    # 相関パラメータ
    correlation_search_space_dimension: 0.6  # 探索範囲を0.5から微増し、マッチングの堅牢性を向上
    correlation_search_space_resolution: 0.01  # 5mm単位でより高精度に
    correlation_search_space_smear_deviation: 0.1  # よりシャープな探索

    # ループクロージャパラメータ
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # スキャンマッチャパラメータ
    distance_variance_penalty: 0.7 # 0.5 -> 0.7 odometryの信頼性を高める（あげなくても結果は良好）
    angle_variance_penalty: 1.2 # 1.0 -> 1.2 odometryの信頼性を高める（あげなくても結果は良好）
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true