slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # プラグインパラメータ
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROSパラメータ
    odom_frame: sirius3/odom
    map_frame: map
    base_frame: sirius3/base_footprint
    scan_topic: /scan3
    use_map_saver: true
    mode: mapping

    debug_logging: true
    throttle_scans: 3  # 全スキャンを処理 1 -> 2 間引いた
    transform_publish_period: 0.02
    map_update_interval: 1.0  # マップ更新を高速化(5.0秒→1.0秒)
    resolution: 0.05
    min_laser_range: 0.0
    max_laser_range: 100.0
    
    # TF関連 - より寛容な設定
    transform_timeout: 1.0  # より寛容に
    tf_buffer_duration: 30.0  # バッファサイズ削減(60→30秒)
    
    # メッセージ処理関連
    minimum_time_interval: 0.1      # 0.1秒ごとに必ず処理
    minimum_laser_range: 0.0
    
    stack_size_to_use: 100000000
    enable_interactive_mode: true
    
    # 一般的なパラメータ
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1   # 10cmごとに処理(より細かく)
    minimum_travel_heading: 0.1     # 約5.7度ごとに処理
    scan_buffer_size: 1000  # メモリ使用量
    scan_buffer_maximum_scan_distance: 10.0  # より厳格に
    link_match_minimum_response_fine: 0.4  # より厳格に(0.1→0.4)
    link_scan_maximum_distance: 2.0  # 探索範囲を広げる
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # 相関パラメータ
    correlation_search_space_dimension: 1.0  # ±1.0mに拡大
    correlation_search_space_resolution: 0.005  # 5mm単位でより高精度に
    correlation_search_space_smear_deviation: 0.05  # よりシャープな探索

    # ループクロージャパラメータ
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # スキャンマッチャパラメータ
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true